WebDienMay/Models/PostTopic.cs
namespace WatchStore
{ 
    using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


    public class PostTopic
    {
        public int PostId { get; set; }
        public string PostName { get; set; }
        public string PostImg { get; set; }
        public int PostStatus { get; set; }
        public string TopicName { get; set; }
        public DateTime PostCreated_At { get; set; }
    }
}

WebDienMay/Controllers/ModuleController.cs
using WatchStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WatchStore.Controllers
{
    public class ModuleController : Controller
    {
        private WatchStoreDbContext db = new WatchStoreDbContext();
        // GET: Module
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Header()
        {
            return View("_Header");
        }
        public ActionResult CategorySearch()
        {
            var list = db.Categorys
               .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("_CategorySearch",list);
        }
        public ActionResult Cart()
        {
            return View("_Cart");
        }
        public ActionResult Navbar()
        {
            return View("_Navbar");
        }
        public ActionResult ProductView()
        {
            return View("_ProductView");
        }
        public ActionResult LatestNew()
        {
            var list = db.Posts
               .Where(m => m.Status == 1 && m.Type == "post")
               .Take(3)
               .OrderByDescending(m => m.Created_At )
               .ToList();
            return View("_LatestNew", list);
        }

        public ActionResult LatestNewListing()
        {
            var list = db.Posts
               .Where(m => m.Status == 1 && m.Type == "post")
               .Take(8)
               .OrderByDescending(m => m.Created_At)
               .ToList();
            return View("_LatestNewListing", list);
        }

        public ActionResult Brand()
        {
            return View("_Brand");
        }
        public ActionResult CompanyFacality()
        {
            return View("_CompanyFacality");
        }
        public ActionResult Footer()
        {
            return View("_Footer");
        }
        public ActionResult Copyright()
        {
            return View("_Copyright");
        }
        public ActionResult LinkHeader()
        {
            return View("_LinkHeader");
        }
        public ActionResult LinkFooter()
        {
            return View("_LinkFooter");
        }
        public ActionResult Category()
        {
            var list = db.Categorys
                .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("_Category", list);
        }

        public ActionResult CategoryChild(int id)
        {
            var list = db.Categorys
                .Where(m => m.Status == 1 && m.ParentId == id);
            return View("_CategoryChild", list);
        }

        public ActionResult CategoryFooter()
        {
            var list = db.Categorys
                .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("_CategoryFooter", list);
        }
        public ActionResult ProductNew()
        {
            var list = db.Products
               .Where(m => m.Status == 1 && m.Discount != 0)
               .Take(8)
               .ToList();
            return View("_ProductNew", list);
        }

        public ActionResult Sale()
        {
            var list = db.Products
               .Where(m => m.Status == 1)
               .Take(8)
               .OrderByDescending(m=>m.Created_at)
               .ToList();
            return View("_Sale", list);
        }


        public ActionResult Sell()
        {
            var list = (from p in db.Products
                        let totalQuantity = (from op in db.Orderdetails
                                             join o in db.Orders on op.OrderId equals o.Id
                                             where op.ProductId == p.ID 
                                             select op.Quantity).Sum()
                        where totalQuantity > 0
                        orderby totalQuantity descending
                        select p).Take(8);
            return View("_Sell", list);
        }

        public ActionResult Feature()
        {
          
            return View("_Feature");
        }

        public ActionResult SlideShow()
        {
            return View("_SlideShow",db.Sliders.Where(m=>m.Status!=0).ToList());
        }
        public ActionResult ListPage()
        {
            var list = db.Posts
              .Where(m => m.Status == 1 && m.Type=="page")
              .OrderByDescending(m => m.Created_At)
              .ToList();
            return View("_ListPage",list);
        }
        public ActionResult MainMenu()
        {
            var list = db.Menus
              .Where(m => m.Status == 1 && m.Position=="mainmenu")
              .ToList();
            return View("_MainMenu", list);
        }

        public ActionResult MainMenuWithCategory()
        {
            var listCat = db.Categorys
              .Where(m => m.Status == 1 && m.ParentId == 0);

            int[] arrayID = new int[] { 8,19 }; // array parent ID

            ViewBag.ListCatID = arrayID;
            return View("_MainMenuWithCategory", listCat);
        }

        public ActionResult MainMenuWithSubCategory(int id)
        {
            var listCat = db.Categorys
              .Where(m => m.Status == 1 && m.ParentId == id);

            return View("_MainMenuWithSubCategory", listCat);
        }
        public ActionResult MainMenuMobile()
        {
            var list = db.Menus
              .Where(m => m.Status == 1 && m.Type == "custom")
              .ToList();
            return View("_MainMenuMobile", list);
        }
        public ActionResult ListCate()
        {
            return View("_ListCate", db.Categorys.Where(m => m.Status != 0 && m.ParentId==0).ToList());
        }
        public ActionResult Posts()
        {
            var list = db.Topics 
                .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("Posts", list);
        }
        public ActionResult PostHome(int topid)
        {
            List<int> listtopid = new List<int>();
            listtopid.Add(topid);

            var list2 = db.Topics
                .Where(m => m.ParentId == topid).Select(m => m.Id)
                .ToList();
            foreach (var id2 in list2)
            {
                listtopid.Add(id2);
                var list3 = db.Topics
                    .Where(m => m.ParentId == id2)
                    .Select(m => m.Id).ToList();
                foreach (var id3 in list3)
                {
                    listtopid.Add(id3);
                }
            }

            var list = db.Posts
                .Where(m => m.Status == 1 && listtopid
                .Contains(m.Topid))
                .Take(12)
                .OrderByDescending(m => m.Created_At);

            return View("PostHome", list);
        }
        public ActionResult ListTopic()
        {
            return View("ListTopic", db.Topics.Where(m => m.Status != 0 && m.ParentId == 0).ToList());
        }
        public ActionResult PListPage()
        {
            var list = db.Posts
                .Where(m => m.Status == 1 && m.Type == "page");
            return View("PListPage", list);
        }
        public ActionResult RecentlyViewedProducts()
        {
            var list = Session["RecentlyViewedProducts"];
            
            return View("_RecentlyViewedProducts", list); ;
            
        }
    }
}

WebDienMay/Controllers/SiteController.cs
using WatchStore.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WatchStore.Controllers
{
    public class SiteController : Controller
    {
        private WatchStoreDbContext db = new WatchStoreDbContext();
        // GET: Site
        public ActionResult Index(String slug = "")
        {
            int pageNumber = 1;
            Session["keywords"] = null;
            if (!string.IsNullOrEmpty(Request.QueryString["page"]))
            {
                pageNumber = int.Parse(Request.QueryString["page"].ToString());
            }
            if (slug == "")
            {
                return this.Home();
            }
            else if (slug.Equals("Dưới 1 triệu") || slug.Equals("Từ 1 - 2 triệu") || slug.Equals("Từ 2 - 3 triệu") || slug.Equals("Từ 3 triệu"))
            {
                return this.ProductPrice(slug, pageNumber);
            }
            else
            {
                var link = db.Links.Where(m => m.Slug == slug);
                if (link.Count() > 0)
                {
                    var res = link.First();
                    if (res.Type == "page")
                    {
                        return this.PostPage(slug);
                    }
                    else if (res.Type == "topic")
                    {
                        return this.PostTopic(slug, pageNumber);
                    }
                    else if (res.Type == "category")
                    {
                        return this.ProductCategory(slug, pageNumber);
                    }
                }
                else
                {
                    if (db.Products.Where(m => m.Slug == slug && m.Status == 1).Count() > 0)
                    {
                        return this.ProductDetail(slug);
                    }
                    else if (db.Posts.Where(m => m.Slug == slug && m.Type == "post" && m.Status == 1).Count() > 0)
                    {
                        return this.PostDetail(slug);
                    }
                }
                return this.Error(slug);
            }
        }

        public ActionResult ProductDetail(String slug)
        {
            //??
            var model = db.Products
                .Where(m => m.Slug == slug && m.Status == 1)
                .First();
            int catid = model.CateID;

            var recentlyViews = (List<MProduct>)Session["RecentlyViewedProducts"];
            MProduct pDelete = null;
            foreach (MProduct p in recentlyViews)
            {
                if (p.ID.Equals(model.ID))
                {
                    pDelete = p;
                    break;
                }
            }

            recentlyViews.Remove(pDelete);
            recentlyViews.Insert(0, model);
            List<int> listcatid = new List<int>();
            listcatid.Add(catid);

            var list2 = db.Categorys
                .Where(m => m.ParentId == catid)
                .Select(m => m.Id)
                .ToList();
            foreach (var id2 in list2)
            {
                listcatid.Add(id2);
                var list3 = db.Categorys
                    .Where(m => m.ParentId == id2)
                    .Select(m => m.Id)
                    .ToList();
                foreach (var id3 in list3)
                {
                    listcatid.Add(id3);
                }
            }
            // danh mục cùng sản phẩm
            ViewBag.listother = db.Products
                .Where(m => m.Status == 1 && listcatid
                .Contains(m.CateID) && m.ID != model.ID)
                .OrderByDescending(m => m.Created_at)
                .Take(12)
                .ToList();
            // sản phẩm mới nhập
            ViewBag.news = db.Products
                .Where(m => m.Status == 1 /*&& listcatid.Contains(m.CatId)*/ && m.ID != model.ID)
                .OrderByDescending(m => m.Created_at).Take(4).ToList();

            ViewBag.Rates = db.Rates.Where(m => m.ProductID == model.ID);

            return View("ProductDetail", model);
        }
        public ActionResult PostDetail(String slug)
        {
            var model = db.Posts
                 .Where(m => m.Slug == slug && m.Status == 1)
                 .First();
            int topid = model.Topid;

            List<int> listtopid = new List<int>();
            listtopid.Add(topid);

            var list2 = db.Topics
                .Where(m => m.ParentId == topid)
                .Select(m => m.Id)
                .ToList();
            foreach (var id2 in list2)
            {
                listtopid.Add(id2);
                var list3 = db.Topics
                    .Where(m => m.ParentId == id2)
                    .Select(m => m.Id)
                    .ToList();
                foreach (var id3 in list3)
                {
                    listtopid.Add(id3);
                }
            }
            // danh mục cùng bài viết
            ViewBag.listother = db.Posts
                .Where(m => m.Status == 1 && listtopid
                .Contains(m.Topid) && m.Id != model.Id)
                .OrderByDescending(m => m.Created_At)
                .Take(12)
                .ToList();

            return View("PostDetail", model);
        }
        public ActionResult Error(String slug)
        {
            return View("Error");
        }

        public ActionResult PostPage(String slug)
        {
            var item = db.Posts
                .Where(m => m.Slug == slug && m.Type == "page")
                 .First();
            return View("PostPage", item);
        }

        public ActionResult PostTopic(String slug, int pageNumber)
        {
            int pageSize = 8;
            var row_cat = db.Topics
                .Where(m => m.Slug == slug)
                .First();
            List<int> listtopid = new List<int>();
            listtopid.Add(row_cat.Id);

            var list2 = db.Topics
                .Where(m => m.ParentId == row_cat.Id)
                .Select(m => m.Id)
                .ToList();
            foreach (var id2 in list2)
            {
                listtopid.Add(id2);
                var list3 = db.Topics
                    .Where(m => m.ParentId == id2)
                    .Select(m => m.Id)
                    .ToList();
                foreach (var id3 in list3)
                {
                    listtopid.Add(id3);
                }
            }
            var list = db.Posts
                .Where(m => m.Status == 1 && listtopid.Contains(m.Topid))
                .OrderByDescending(m => m.Created_At);


            ViewBag.Slug = slug;
            ViewBag.CatName = row_cat.Name;
            return View("PostTopic", list
                .ToPagedList(pageNumber, pageSize));
        }
        public ActionResult ProductPrice(string slug, int pageNumber)
        {
            int pageSize = 16;
            double start = 0;
            double end = 0;
            if (slug.Equals("Dưới 3 triệu"))
            {
                start = 0;
                end = 3000000;
            }
            else if (slug.Equals("Từ 3 - 5 triệu"))
            {
                start = 3000000;
                end = 5000000;
            }
            else if (slug.Equals("Từ 5 - 7 triệu"))
            {
                start = 5000000;
                end = 7000000;
            }
            else if (slug.Equals("Trên 7 triệu"))
            {
                start = 7000000;
                end = 1000000000000;
            }
            var listt = db.Products
            .Where(m => m.Status == 1 && m.Price > start && m.Price < end)
            .OrderByDescending(m => m.Created_at);

            ViewBag.Slug = "Sản phẩm " + slug;
            ViewBag.CatName = slug;
            ViewBag.Sl = listt.Count();
            return View("ProductCategory", listt
                .ToPagedList(pageNumber, pageSize));

        }
        public ActionResult ProductCategory(String slug, int pageNumber)
        {

            int pageSize = 16;
            var row_cat = db.Categorys
                .Where(m => m.Slug == slug)
                .First();
            List<int> listcatid = new List<int>();
            listcatid.Add(row_cat.Id);

            var list2 = db.Categorys
                .Where(m => m.ParentId == row_cat.Id)
                .Select(m => m.Id)
                .ToList();
            foreach (var id2 in list2)
            {
                listcatid.Add(id2);
                var list3 = db.Categorys
                    .Where(m => m.ParentId == id2)
                    .Select(m => m.Id)
                    .ToList();
                foreach (var id3 in list3)
                {
                    listcatid.Add(id3);
                }
            }
            var list = db.Products
                .Where(m => m.Status == 1 && listcatid.Contains(m.CateID))
                .OrderByDescending(m => m.Created_at);

            ViewBag.Slug = slug;
            ViewBag.CatName = row_cat.Name;
            ViewBag.Sl = db.Products.Where(m => m.Status != 0 && m.CateID == row_cat.Id).Count();
            return View("ProductCategory", list
                .ToPagedList(pageNumber, pageSize));
        }


        //Trang Chủ
        public ActionResult Home()
        {
            var list = db.Categorys
               .Where(m => m.Status == 1 && m.ParentId == 0)
               .Take(8)
               .ToList();
            return View("Home", list);
        }
        public ActionResult Other()
        {
            return View("Other");
        }
        //Sản phẩm trang chủ
        public ActionResult ProductHome(int catid)
        {
            List<int> listcatid = new List<int>();
            listcatid.Add(catid);

            var list2 = db.Categorys
                .Where(m => m.ParentId == catid).Select(m => m.Id)
                .ToList();
            foreach (var id2 in list2)
            {

WebDienMay/Views/Site/Home.cshtml
@model IEnumerable<WatchStore.Models.MCategory>
@{
    ViewBag.Title = "Điện Máy GUT";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@Html.Action("Navbar", "Module")
@Html.Action("ProductView", "Module")

WebDienMay/Views/Site/PostDetail.cshtml
@model WatchStore.Models.MPost
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            @Html.Raw(Model.Detail)
        </div>
        <div class="col-md-2"></div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="left-title-area">
                <h2 class="left-title">Bài viết cùng danh mục</h2>
            </div>
        </div>
        <div class="related-product-area featured-products-area">
            <div class="col-sm-12">
                <div class=" row">
                    <div class="related-product">
                        @foreach (var item in ViewBag.listother)
                        {
                            <div class="item">
                                <div class="single-product-item">
                                    <div class="product-image">
                                        <a href="~/@item.Slug"><img src="~/Public/library/post/@item.Img" alt="@item.Title" height="120px;" /></a>
                                    </div>
                                    <div class="product-info">
                                        <a href="@item.Slug">@item.Title</a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebDienMay/Views/Site/PostPage.cshtml
@model WatchStore.Models.MPost
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<div class="post-page">
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                @Html.Raw(Model.Detail)
            </div>
            <div class="col-md-2"></div>
        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <h2 style="color:darkgoldenrod">Xem thêm</h2>
                @Html.Action("PListPage", "Module")
                <div class="fb-comments" data-href="@Request.Url.GetLeftPart(UriPartial.Path)" data-width="100%" data-numposts=""></div>

            </div>
            <div class="col-md-2">

            </div>

        </div>

    </div>
</div>

WebDienMay/Views/Site/PostTopic.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<WatchStore.Models.MPost>
@{ ViewBag.Title = ViewBag.CatName;
                Layout = "~/Views/Shared/_LayoutSite.cshtml"; }

<section class="main-content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <!-- BSTORE-BREADCRUMB START -->
                <div class="bstore-breadcrumb">
                    <a href="~/">Trang chủ</a>
                    <span><i class="fa fa-caret-right"></i></span>
                    <span>@ViewBag.CatName</span>
                </div>
                <!-- BSTORE-BREADCRUMB END -->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <!-- PRODUCT-LEFT-SIDEBAR START -->
                <div class="product-left-sidebar">
                    <h2 class="left-title pro-g-page-title">Danh mục bài viết</h2>
                    <!-- SINGLE SIDEBAR ENABLED FILTERS START -->
                    <ul>
                        @Html.Action("ListTopic", "Module")
                    </ul>
                </div>
                <!-- PRODUCT-LEFT-SIDEBAR END -->
                <!-- SINGLE SIDEBAR TAG START -->
                <div class="product-left-sidebar">
                    <h2 class="left-title">Tags </h2>
                    <div class="category-tag">
                      
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <div class="all-gategory-product">
                    <div class="row">
                        <ul class="gategory-product">
                            @foreach (var item in Model)
                            {
                <li class="gategory-product-list col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="single-product-item">
                        <div class="product-image">
                            <a href="~/@item.Slug"><img src="~/Public/library/post/@item.Img" alt="@item.Title" width="120px;" /></a>
                            
                            
                        </div>
                        <div class="product-info">
                            <div class="customar-comments-box">
                               @* <div class="rating-box">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>*@
                                @*<div class="review-box">
                                        <span>1 Review(s)</span>
                                    </div>*@
                            </div>
                            <a href="~/@item.Slug">@item.Title</a>
                            
                        </div>
                    </div>
                </li>}
                        </ul>
                    </div>
                </div>
                <div class="product-shooting-result product-shooting-result-border">

                    @*<div class="showing-item">
                        <span>Showing 1 - 12 of @ViewBag.Sl</span>
                    </div>*@
                    <div class="showing-next-prev">
                        @Html.PagedListPager(Model, page => Url.Action("Index", "Site", new { slug = ViewBag.Slug, page }))

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

WebDienMay/Views/Site/ProductCategory.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<WatchStore.Models.MProduct>
@{
    ViewBag.Title = ViewBag.CatName;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<section class="main-content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <!-- BSTORE-BREADCRUMB START -->
                <div class="bstore-breadcrumb">
                    <a href="~/">Trang chủ</a>
                    <span><i class="fa fa-caret-right"></i></span>
                    <span>@ViewBag.CatName</span>
                </div>
                <!-- BSTORE-BREADCRUMB END -->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">

                <div class="left-category-menu">
                    <div class="left-product-cat">
                        <div class="category-heading">
                            <h2>DANH MỤC</h2>
                        </div>
                        <div class="category-menu-list">
                            @Html.Action("Category", "Module")
                        </div>
                    </div>
                </div>

                <div class="left-category-menu">
                    <div class="left-product-cat">
                        <div class="category-heading">
                            <h2>ĐIỆN MÁY</h2>
                        </div>
                        <div class="category-menu-list">
                            @Html.Action("CategoryChild", "Module", new { id = 8 })
                        </div>
                    </div>
                </div>

                <div class="left-category-menu">
                    <div class="left-product-cat">
                        <div class="category-heading">
                            <h2>ĐIỆN TỬ</h2>
                        </div>
                        <div class="category-menu-list">
                            @Html.Action("CategoryChild", "Module", new { id = 19 })
                        </div>
                    </div>
                </div>

                

                <div class="left-category-menu">
                    <div class="left-product-cat">
                        <div class="category-heading">
                            <h2>Sản phẩm vừa xem</h2>
                        </div>
                        <div class="category-menu-list">
                            @Html.Action("RecentlyViewedProducts", "Module")
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <div class="all-gategory-product">
                    <div class="row">
                        <ul class="gategory-product">
                            @foreach (var item in Model)
                            {
                                <li class="gategory-product-list col-lg-3 col-md-4 col-sm-6 col-xs-12">
                                    <div class="single-product-item">
                                        <div class="product-image">
                                            <a href="~/@item.Slug"><img src="~/Public/library/product/@item.Image" alt="@item.Name" /></a>
                                            @if (item.Discount != 0)
                                            {
                                        <a href="#" class="new-mark-box">new</a> 
                                            }
                                             else
                                               {
                                                  @*<a href="#" class="new-mark-box">new</a>*@
                                                }
                                            <div class="overlay-content">
                                                <ul>
                                                    
                                                    <li><a href="@item.Slug" title="Xem chi tiết"><i class="fa fa-shopping-cart"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-heart-o"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="product-info">
                                            <div class="customar-comments-box">

                                                @*<div class="review-box">
                <span>1 Review(s)</span>
            </div>*@
                                            </div>
                                            <a href="~/@item.Slug">@item.Name</a>

                                            <div class="price-box">
                                                @if (item.Discount == 1)
                                                {
                                        <span class="price">@String.Format("{0:0,0₫}", item.ProPrice)</span>
                                                            <del><span class="price" style="color:red">@String.Format("{0:0,0₫}", item.Price)</span></del> }
                                                                            else
                                                                            {
                                                            <span class="price" style="color:red">@String.Format("{0:0,0₫}", item.Price)</span>}


                                            </div>
                                            <div>
                                                @for (int i = 1; i <= 5; i++)
                                                {
                                                    if (i <= item.ProRate)
                                                    {
                                                        <span class="fa fa-star checked"></span>
                                                    }
                                                    else
                                                    {
                                                        <span class="fa fa-star"></span>
                                                    }
                                                }
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="product-shooting-result product-shooting-result-border">

                    <div class="showing-item">
                        <span>Showing 1 - 12 of @ViewBag.Sl</span>
                    </div>
                    <div class="showing-next-prev">
                        @Html.PagedListPager(Model, page => Url.Action("Index", "Site", new { slug = ViewBag.Slug, page }))

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>